[theme]
base = "light"
primaryColor = "#1565C0"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#424242"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
